import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss';
import Footer from '@/components/Footer';

const Home: NextPage = () => {
  return (
    <div className={styles.Layout}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header className={styles.header}>
         header
      </header>

      <main className={styles.main}>
        <h3>
         {process.env.NEXT_PUBLIC_API_URL}
        </h3>
      </main>

      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  )
}

export default Home
